
## set the data directories and data files ##
infile: "https://dapds00.nci.org.au/thredds/dodsC/zv2/agcd/v1-0-1/tmax/mean/r005/01day/agcd_v1-0-1_tmax_mean_r005_daily_2022.nc"
var_i: "tmax"
## if you are using the demo data
rootdir: "data_provided"
indir_sa1: "ABS_Census_2016/abs_sa1_2016_data_provided"
## dir(indir_sa1)
infile_sa1: "SA1_2016_WA.shp"
popdir: "ABS_GCP_2016/data_provided/SA1/AUST"
popfile: "2016Census_G01_AUS_SA1.csv"
  
## alternately if you have cloud-car-dat mounted  
## rootdir: "~/cloud-car-dat/Shared/"
## indir_sa1: "Environment_General/ABS_data/ABS_Census_2016/abs_sa1_2016_data_provided"
## infile_sa1: "SA1_2016_NSW.shp"

dat_derived_dir: "data_derived"
